// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "GoGoMio Support"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/api/config": {
            "get": {
                "description": "Returns camera configuration and current metrics. This endpoint combines two concerns; use /v1/config/camera for static config or /v1/metrics/live for metrics instead",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configuration"
                ],
                "summary": "Get configuration and metrics (DEPRECATED - use /v1/config/camera and /v1/metrics/live)",
                "deprecated": true,
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/api/diagnostics": {
            "get": {
                "description": "Returns complete system diagnostics. This endpoint is deprecated; use /v1/health/detailed instead",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Diagnostics"
                ],
                "summary": "Get comprehensive diagnostics (DEPRECATED - use /v1/health/detailed)",
                "deprecated": true,
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.DetailedHealthResponse"
                        }
                    }
                }
            }
        },
        "/v1/api/settings": {
            "get": {
                "description": "Retrieves all saved application settings",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Settings"
                ],
                "summary": "Get all settings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "description": "Updates one or more application settings. Accepts both POST and PUT requests",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Settings"
                ],
                "summary": "Update settings",
                "parameters": [
                    {
                        "description": "Settings to update",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SettingsUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Updates one or more application settings. Accepts both POST and PUT requests",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Settings"
                ],
                "summary": "Update settings",
                "parameters": [
                    {
                        "description": "Settings to update",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SettingsUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/status": {
            "get": {
                "description": "Returns detailed status. This endpoint is deprecated; use /v1/health/detailed instead",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Get system status (DEPRECATED - use /v1/health/detailed)",
                "deprecated": true,
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResponse"
                        }
                    }
                }
            }
        },
        "/v1/api/stream/stop": {
            "post": {
                "description": "Stops the camera stream capture and disconnects all clients",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Streaming"
                ],
                "summary": "Stop stream capture",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/config/camera": {
            "get": {
                "description": "Returns static camera configuration settings",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configuration"
                ],
                "summary": "Get camera configuration (static)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CameraConfigResponse"
                        }
                    }
                }
            }
        },
        "/v1/health": {
            "get": {
                "description": "Returns the current health status of the camera system including uptime, FPS, and connection count\nReturns the current health status of the camera system including uptime, FPS, and connection count",
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "Health",
                    "Health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/health/detailed": {
            "get": {
                "description": "Returns comprehensive health status with detailed metrics, error tracking, and diagnostics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Get detailed health and metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.DetailedHealthResponse"
                        }
                    }
                }
            }
        },
        "/v1/metrics/live": {
            "get": {
                "description": "Returns current performance and connection metrics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Get live metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.LiveMetricsResponse"
                        }
                    }
                }
            }
        },
        "/v1/ready": {
            "get": {
                "description": "Returns 200 if camera is ready, 503 if still initializing",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/snapshot.jpg": {
            "get": {
                "description": "Returns the latest captured frame as a JPEG image",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "image/jpeg"
                ],
                "tags": [
                    "Streaming"
                ],
                "summary": "Get current snapshot",
                "responses": {
                    "200": {
                        "description": "JPEG image data",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "503": {
                        "description": "Camera not ready",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.CameraConfigResponse": {
            "description": "Camera configuration, resolution, and streaming performance metrics",
            "type": "object",
            "properties": {
                "api_version": {
                    "description": "API version",
                    "type": "string",
                    "example": "1"
                },
                "fps": {
                    "description": "Configured frames per second",
                    "type": "integer",
                    "example": 30
                },
                "jpeg_quality": {
                    "description": "JPEG compression quality (0-100)",
                    "type": "integer",
                    "example": 85
                },
                "max_stream_connections": {
                    "description": "Maximum concurrent stream connections allowed",
                    "type": "integer",
                    "example": 5
                },
                "resolution": {
                    "description": "Camera resolution in pixels [width, height]",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "target_fps": {
                    "description": "Target FPS for frame buffer",
                    "type": "integer",
                    "example": 30
                },
                "timestamp_iso8601": {
                    "description": "ISO8601 timestamp of this response",
                    "type": "string",
                    "example": "2026-04-19T15:30:45Z"
                }
            }
        },
        "api.DetailedHealthResponse": {
            "description": "Comprehensive health status with detailed metrics, error tracking, and diagnostics",
            "type": "object",
            "properties": {
                "api_version": {
                    "description": "API version",
                    "type": "string",
                    "example": "1"
                },
                "camera_ready": {
                    "description": "Whether the camera is initialized and ready",
                    "type": "boolean",
                    "example": true
                },
                "capture_failures_consecutive": {
                    "description": "Consecutive capture failures (resets on success)",
                    "type": "integer",
                    "example": 0
                },
                "capture_failures_total": {
                    "description": "Total capture failures since startup",
                    "type": "integer",
                    "example": 10
                },
                "capture_restart_count": {
                    "description": "Number of times capture has been restarted",
                    "type": "integer",
                    "example": 2
                },
                "degraded": {
                    "description": "Whether system is operating in degraded mode",
                    "type": "boolean",
                    "example": false
                },
                "error_rate_percent": {
                    "description": "Error rate as percentage",
                    "type": "number",
                    "example": 0.5
                },
                "fps_configured": {
                    "description": "Configured frames per second",
                    "type": "integer",
                    "example": 30
                },
                "fps_current": {
                    "description": "Current frames per second",
                    "type": "number",
                    "example": 29.8
                },
                "frame_sequence_number": {
                    "description": "Frame sequence number (increments per frame)",
                    "type": "integer",
                    "example": 216001
                },
                "frames_captured": {
                    "description": "Total frames captured since startup",
                    "type": "integer",
                    "example": 216000
                },
                "health_status": {
                    "description": "Health status text: Excellent, Degraded, Poor",
                    "type": "string",
                    "example": "Excellent"
                },
                "jpeg_quality": {
                    "description": "JPEG quality setting (0-100)",
                    "type": "integer",
                    "example": 85
                },
                "last_frame_age_seconds": {
                    "description": "Age of the most recent frame in seconds",
                    "type": "number",
                    "example": 0.034
                },
                "max_stream_connections": {
                    "description": "Maximum concurrent connections",
                    "type": "integer",
                    "example": 5
                },
                "message": {
                    "description": "Detailed status message",
                    "type": "string",
                    "example": "Camera is functioning normally"
                },
                "resolution": {
                    "description": "Resolution as string (e.g., '1920x1080')",
                    "type": "string",
                    "example": "1920x1080"
                },
                "status": {
                    "description": "Overall status: ok, degraded, error",
                    "type": "string",
                    "example": "ok"
                },
                "stream_connections": {
                    "description": "Current number of active stream connections",
                    "type": "integer",
                    "example": 1
                },
                "timestamp_iso8601": {
                    "description": "ISO8601 timestamp of this response",
                    "type": "string",
                    "example": "2026-04-19T15:30:45Z"
                },
                "uptime_seconds": {
                    "description": "System uptime in seconds",
                    "type": "integer",
                    "example": 7200
                }
            }
        },
        "api.HealthResponse": {
            "description": "Quick health status (suitable for Kubernetes probes)",
            "type": "object",
            "properties": {
                "api_version": {
                    "description": "API version",
                    "type": "string",
                    "example": "1"
                },
                "camera_ready": {
                    "description": "Whether the camera is initialized and ready",
                    "type": "boolean",
                    "example": true
                },
                "degraded": {
                    "description": "Whether system is operating in degraded mode",
                    "type": "boolean",
                    "example": false
                },
                "fps_current": {
                    "description": "Current frames per second",
                    "type": "number",
                    "example": 29.8
                },
                "status": {
                    "description": "Overall status: ok, degraded, error",
                    "type": "string",
                    "example": "ok"
                },
                "stream_connections": {
                    "description": "Current number of active stream connections",
                    "type": "integer",
                    "example": 2
                },
                "timestamp_iso8601": {
                    "description": "ISO8601 timestamp of this response",
                    "type": "string",
                    "example": "2026-04-19T15:30:45Z"
                },
                "uptime_seconds": {
                    "description": "System uptime in seconds",
                    "type": "integer",
                    "example": 3600
                }
            }
        },
        "api.LiveMetricsResponse": {
            "description": "Current performance and connection metrics",
            "type": "object",
            "properties": {
                "api_version": {
                    "description": "API version",
                    "type": "string",
                    "example": "1"
                },
                "fps_configured": {
                    "description": "Configured target frames per second",
                    "type": "integer",
                    "example": 30
                },
                "fps_current": {
                    "description": "Current frames per second being delivered",
                    "type": "number",
                    "example": 29.8
                },
                "frame_sequence_number": {
                    "description": "Frame sequence number (increments per frame, useful for detecting gaps)",
                    "type": "integer",
                    "example": 216001
                },
                "frames_captured": {
                    "description": "Total frames captured since startup",
                    "type": "integer",
                    "example": 216000
                },
                "last_frame_age_seconds": {
                    "description": "Age of the most recent frame in seconds",
                    "type": "number",
                    "example": 0.034
                },
                "stream_connections": {
                    "description": "Current number of active stream connections",
                    "type": "integer",
                    "example": 2
                },
                "timestamp_iso8601": {
                    "description": "ISO8601 timestamp of this response",
                    "type": "string",
                    "example": "2026-04-19T15:30:45Z"
                },
                "uptime_seconds": {
                    "description": "System uptime in seconds",
                    "type": "integer",
                    "example": 7200
                }
            }
        },
        "api.SettingsUpdateRequest": {
            "description": "Request body for updating multiple settings at once",
            "type": "object",
            "properties": {
                "settings": {
                    "description": "Map of setting keys to values",
                    "type": "object",
                    "additionalProperties": true
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "GoGoMio API",
	Description:      "IP camera streaming and management API with MJPEG and health monitoring",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
